version: "3.8"

services:
  database:
    env_file:
      - .env
    image: postgres:latest
    user: root
    container_name: small-bank-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - dev-network
    volumes:
      - ../../docker/volumes/postgres:/var/lib/postgresql/data
  #redis:
  #    env_file:
  #        - .env
  #    container_name: promentoria-redis
  #    image: "redis:7.2.1-alpine"
  #    ports:
  #        - "${REDIS_PORT}:${REDIS_PORT}"
  #    volumes:
  #        - redis_data:/data
  #    environment:
  #        - REDIS_HOST=${REDIS_HOST}
  #        - REDIS_PORT=${REDIS_PORT}
  #    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
  #    networks:
  #        - dev-network
  #    depends_on:
  #        - database
networks:
  dev-network:
    driver: bridge
volumes:
  #redis_data:
  postgres_data:
